# EightPoints GuzzleBundle
# A full list of configuration options can be found here:
# https://github.com/8p/EightPointsGuzzleBundle/blob/master/src/Resources/doc/configuration-reference.md
eight_points_guzzle:
    clients:
        riot_api:
            # Not actual url as the adapter needs to set region in domain anyway
            base_url: "https://api.riotgames/lol"
            options:
                headers:
                    Accept: "applicaiton/json"