#parser:
#    resource: "@LeagueOfData/Controller/"
#    type:     annotation

home:
    path:       /
    defaults:   { _controller: LeagueOfData:Default:index }

champion-byId:
    path:       /champion/id
    defaults:   { _controller: LeagueOfData:Champion:byId }