services:
    api-adapter:
        class: LeagueOfData\Adapters\API\ApiAdapter
        arguments: ['@logger', '%apiKey%']
    sql-adapter:
        class: LeagueOfData\Adapters\SQL\SqlAdapter
        arguments: ['@logger', '@database_connection']
    rabbitmq:
        class: LeagueOfData\Service\RabbitMQ
        arguments: ['@logger']
    champion-api:
        class: LeagueOfData\Service\Json\JsonChampions
        arguments: ['@api-adapter', '@logger']
    item-api:
        class: LeagueOfData\Service\Json\JsonItems
        arguments: ['@api-adapter', '@logger']
    version-api:
        class: LeagueOfData\Service\Json\JsonVersions
        arguments: ['@api-adapter', '@logger']
    champion-db:
        class: LeagueOfData\Service\Sql\SqlChampions
        arguments: ['@sql-adapter', '@logger']
    item-db:
        class: LeagueOfData\Service\Sql\SqlItems
        arguments: ['@sql-adapter', '@logger']
    version-db:
        class: LeagueOfData\Service\Sql\SqlVersions
        arguments: ['@sql-adapter', '@logger']