services:
    guzzle:
        class: GuzzleHttp\Client
        arguments: []
    api-adapter:
        class: LeagueOfData\Adapters\ApiAdapter
        arguments: ['@logger', '@guzzle', '%apiKey%']
    sql-adapter:
        class: LeagueOfData\Adapters\SqlAdapter
        arguments: ['@logger', '@database_connection']
    rabbitmq:
        class: LeagueOfData\Service\RabbitMQ
        arguments: ['@logger']
    champion-stat-api:
        class: LeagueOfData\Service\Json\JsonChampionStats
        arguments: ['@api-adapter', '@logger']
    champion-spell-api:
        class: LeagueOfData\Service\Json\JsonChampionSpells
        arguments: ['@api-adapter', '@logger']
    champion-api:
        class: LeagueOfData\Service\Json\JsonChampions
        arguments: ['@api-adapter', '@logger', '@champion-stat-api', '@champion-spell-api']
    item-api:
        class: LeagueOfData\Service\Json\JsonItems
        arguments: ['@api-adapter', '@logger']
    version-api:
        class: LeagueOfData\Service\Json\JsonVersions
        arguments: ['@api-adapter', '@logger']
    realm-api:
        class: LeagueOfData\Service\Json\JsonRealms
        arguments: ['@api-adapter', '@logger']
    champion-stat-db:
        class: LeagueOfData\Service\Sql\SqlChampionStats
        arguments: ['@sql-adapter', '@logger']
    champion-spell-db:
        class: LeagueOfData\Service\Sql\SqlChampionSpells
        arguments: ['@sql-adapter', '@logger']
    champion-db:
        class: LeagueOfData\Service\Sql\SqlChampions
        arguments: ['@sql-adapter', '@logger', '@champion-stat-db', '@champion-spell-db']
    item-db:
        class: LeagueOfData\Service\Sql\SqlItems
        arguments: ['@sql-adapter', '@logger']
    version-db:
        class: LeagueOfData\Service\Sql\SqlVersions
        arguments: ['@sql-adapter', '@logger']
    realm-db:
        class: LeagueOfData\Service\Sql\SqlRealms
        arguments: ['@sql-adapter', '@logger']
